
package com.epam.roman.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "UserService", targetNamespace = "http://ws.roman.epam.com/")
@SOAPBinding(style = SOAPBinding.Style.RPC)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UserService {


    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://ws.roman.epam.com/UserService/deleteUserRequest", output = "http://ws.roman.epam.com/UserService/deleteUserResponse")
    public void deleteUser(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @param arg0
     */
    @WebMethod
    @Action(input = "http://ws.roman.epam.com/UserService/addUserRequest", output = "http://ws.roman.epam.com/UserService/addUserResponse")
    public void addUser(
        @WebParam(name = "arg0", partName = "arg0")
        User arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.epam.roman.ws.User
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.roman.epam.com/UserService/getUserRequest", output = "http://ws.roman.epam.com/UserService/getUserResponse")
    public User getUser(
        @WebParam(name = "arg0", partName = "arg0")
        int arg0);

    /**
     * 
     * @return
     *     returns com.epam.roman.ws.UserArray
     */
    @WebMethod
    @WebResult(partName = "return")
    @Action(input = "http://ws.roman.epam.com/UserService/getAllUsersRequest", output = "http://ws.roman.epam.com/UserService/getAllUsersResponse")
    public UserArray getAllUsers();

}
